using System.Collections.ObjectModel;
using System.Windows;
using BreakoutAlerts.Core.Abstractions;
using BreakoutAlerts.Core.Configuration;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;

namespace BreakoutAlerts.App.ViewModels;

/// <summary>
/// Root ViewModel. Owns the navigation rail, the currently displayed page and the
/// connection status shown in the title bar.
/// </summary>
public sealed partial class ShellViewModel : ObservableObject
{
    private readonly IMarketDataProvider _marketData;
    private readonly Services.OpenDLauncher? _launcher;

    /// <summary>Items shown in the left navigation rail.</summary>
    public ObservableCollection<NavigationItem> NavigationItems { get; }

    /// <summary>The page currently filling the content area.</summary>
    [ObservableProperty]
    private PageViewModelBase? _currentPage;

    /// <summary>The selected rail entry. Setting it navigates.</summary>
    [ObservableProperty]
    private NavigationItem? _selectedItem;

    /// <summary>Whether the data provider currently has a usable connection.</summary>
    [ObservableProperty]
    private bool _isConnected;

    /// <summary>Connection state as display text.</summary>
    [ObservableProperty]
    private string _connectionStatus = "Connecting…";

    /// <summary>
    /// Data source description shown beside the status pill.
    /// </summary>
    /// <remarks>
    /// Hard-coded to "Simulated feed" for Phase 1, and deliberately prominent. An app that
    /// looks live but is showing generated numbers is genuinely dangerous if it is ever
    /// mistaken for the real thing - the label makes that impossible to confuse.
    /// </remarks>
    [ObservableProperty]
    private string _dataSourceLabel = "moomoo OpenD";

    /// <summary>True when the application is running on generated data.</summary>
    /// <remarks>
    /// Drives a persistent banner rather than a small label. Synthetic prices that look
    /// real are the most damaging thing this application could show, so the indication has
    /// to be impossible to overlook rather than merely present.
    /// </remarks>
    [ObservableProperty]
    private bool _isSyntheticData;

    /// <summary>Creates the shell and wires the rail to the page ViewModels.</summary>
    public ShellViewModel(
        IMarketDataProvider marketData,
        MarketDataOptions marketDataOptions,
        Services.OpenDLauncher? launcher,
        DashboardViewModel dashboard,
        ScannerViewModel scanner,
        TradingViewModel trading,
        StrategiesViewModel strategies)
    {
        _marketData = marketData ?? throw new ArgumentNullException(nameof(marketData));
        _launcher = launcher;

        NavigationItems =
        [
            // Glyph code points from Segoe Fluent Icons, which ships with Windows 11.
            // Written as \u escapes rather than pasted characters: these live in the
            // Unicode private use area, where the glyph is invisible in most editors and
            // is silently mangled by any tool that re-encodes the file. A placeholder box
            // on screen just means a wrong code point - purely cosmetic to fix.
            new NavigationItem("Dashboard", "\uE7ED", dashboard), // Ringer
            new NavigationItem("Scanner", "\uE8A9", scanner), // ViewAll
            new NavigationItem("Trading", "\uE7BF", trading), // Shop
            new NavigationItem("Strategies", "\uE713", strategies) // Setting
        ];

        IsSyntheticData = marketDataOptions.IsSynthetic;
        DataSourceLabel = marketDataOptions.IsSynthetic
            ? "SYNTHETIC DATA - NOT REAL PRICES"
            : $"moomoo OpenD {marketDataOptions.Host}:{marketDataOptions.Port}";

        _marketData.ConnectionStateChanged += OnConnectionStateChanged;
        UpdateConnectionState(_marketData.IsConnected);

        // "Trade this candidate" fills a ticket on the Trading page, so the shell follows it
        // there. The dashboard raises an event rather than navigating itself - only the shell
        // knows what pages exist.
        dashboard.TradeRequested += (_, _) =>
            SelectedItem = NavigationItems.FirstOrDefault(i => i.Page is TradingViewModel);

        // Land on the scanner. Starting with a blank content area makes a freshly launched
        // app look broken.
        SelectedItem = NavigationItems[0];
    }

    /// <summary>Navigates when the rail selection changes.</summary>
    /// <remarks>
    /// Generated by the MVVM Toolkit's source generator from the
    /// <see cref="SelectedItem"/> property - it emits a partial method hook that runs
    /// after the value changes.
    /// </remarks>
    partial void OnSelectedItemChanged(NavigationItem? value)
    {
        if (value is null)
        {
            return;
        }

        CurrentPage = value.Page;

        // Fire-and-forget activation. Awaiting here would mean blocking the setter, and a
        // property setter cannot be async. Exceptions are contained inside the page's own
        // OnActivatedAsync rather than being allowed to escape onto the dispatcher.
        _ = value.Page.OnActivatedAsync();
    }

    private void OnConnectionStateChanged(object? sender, bool connected)
    {
        // The provider raises this from a background thread, so marshal before touching
        // bound properties. Without the dispatch, WPF throws on the binding update - and
        // only sometimes, depending on timing.
        var dispatcher = Application.Current?.Dispatcher;
        if (dispatcher is not null && !dispatcher.CheckAccess())
        {
            dispatcher.Invoke(() => UpdateConnectionState(connected));
            return;
        }

        UpdateConnectionState(connected);
    }

    private void UpdateConnectionState(bool connected)
    {
        IsConnected = connected;
        ConnectionStatus = connected ? "Connected" : "Disconnected";
        OnPropertyChanged(nameof(CanLaunchGateway));
    }

    /// <summary>Message from the last launch attempt, or null.</summary>
    [ObservableProperty]
    private string? _gatewayMessage;

    /// <summary>
    /// True when offering to start OpenD makes sense.
    /// </summary>
    /// <remarks>
    /// Hidden while connected and while running on generated data - in the synthetic case
    /// there is no gateway involved and the button would be nonsense.
    /// </remarks>
    public bool CanLaunchGateway => !IsConnected && !IsSyntheticData && _launcher is not null;

    /// <summary>
    /// Starts OpenD.
    /// </summary>
    /// <remarks>
    /// Bound to a button, never called automatically. After a reboot the gateway is usually
    /// not running and this application can do nothing without it - but launching another
    /// program, which then asks for a login, is a visible side effect and belongs to an
    /// explicit click rather than to a reconnect loop firing while the user is elsewhere.
    ///
    /// <para>The connection is not forced here either. The provider's own reconnect notices
    /// the gateway once it is up and logged in, which can take several seconds.</para>
    /// </remarks>
    [RelayCommand]
    private void LaunchGateway()
    {
        GatewayMessage = _launcher?.Launch();
    }
}

/// <summary>One entry in the navigation rail.</summary>
/// <param name="Label">Text shown in the rail.</param>
/// <param name="Glyph">Segoe Fluent Icons code point.</param>
/// <param name="Page">ViewModel displayed when this entry is selected.</param>
public sealed record NavigationItem(string Label, string Glyph, PageViewModelBase Page);
